version: '3.9'
services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    container_name: tinitiate-dynamodb
    ports:
      - '8500:8000'
    volumes:
      - './dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal
    networks:
      - tinitiate
networks:
  tinitiate:
    name: tinitiate
    external: true
